(define (problem robot-object-move-prob01)
  (:domain robot-object-move)
  (:objects r1 r2 r3 r4 r5 r6 r7 r8 r9 ob1 ob2 ob3 one)
  (:init (room r1)
         (room r2)
         (room r3)
         (room r4)
         (room r5)
         (room r6)
         (room r7)
         (room r8)
         (room r9)
         (object ob1)
         (object ob2)
         (object ob3)
         (robot one)
         (free one)
         (freeroom r1)
	 (freeroom r2) 
	 (freeroom r3)
 	 (freeroom r5)
 	 (freeroom r8)
 	 (freeroom r9)
         (wall r1 r2)
         (wall r2 r1)
         (wall r2 r5)
         (wall r5 r2)
         (wall r4 r7)
         (wall r7 r4)
         (wall r8 r9)
         (wall r9 r8)
         (at-room r1)
         (at ob1 r6)
         (at ob2 r4)
         (at ob3 r7)
         (allow r1 r2)
         (allow r1 r4)
         (allow r2 r1) 
         (allow r2 r3) 
         (allow r2 r5) 
         (allow r3 r2) 
         (allow r3 r6)
         (allow r4 r1) 
         (allow r4 r5) 
	 (allow r4 r7) 
         (allow r5 r2) 
	 (allow r5 r4) 
	 (allow r5 r6) 
	 (allow r5 r8)
         (allow r6 r3) 
	 (allow r6 r5) 
	 (allow r6 r9)
         (allow r7 r4) 
	 (allow r7 r8)
         (allow r8 r5) 
	 (allow r8 r7)
         (allow r8 r9)
         (allow r9 r6)
         (allow r9 r8))

(:goal (and (at ob1 r7)
            (at ob2 r2)
            (at ob3 r9))))
